import { describe, it, expect } from "bun:test";
import { GRID_STYLES, gridFamilyAngles, latticeSnap, isAngledGrid } from "./grid-lattice";

const G = 20;

describe("grid families", () => {
    it("square styles draw no angled families", () => {
        expect(gridFamilyAngles('lines')).toEqual([]);
        expect(gridFamilyAngles('dots')).toEqual([]);
    });

    it("diagonal is two families at ±45°", () => {
        const deg = gridFamilyAngles('diagonal').map(a => Math.round((a * 180) / Math.PI));
        expect(deg).toEqual([45, -45]);
    });

    it("isometric is ±30° plus a vertical", () => {
        // The two 30° families make the rhombus lattice; the vertical is what makes it read
        // as a box rather than as argyle.
        const deg = gridFamilyAngles('isometric').map(a => Math.round((a * 180) / Math.PI));
        expect(deg).toEqual([30, -30, 90]);
    });

    it("knows which styles are angled", () => {
        expect(isAngledGrid('diagonal')).toBe(true);
        expect(isAngledGrid('isometric')).toBe(true);
        expect(isAngledGrid('lines')).toBe(false);
        expect(isAngledGrid('dots')).toBe(false);
    });

    it("exposes every style exactly once, with a label", () => {
        const ids = GRID_STYLES.map(s => s.id);
        expect(new Set(ids).size).toBe(ids.length);
        expect(ids).toContain('lines');
        expect(ids).toContain('dots');
        expect(ids).toContain('diagonal');
        expect(ids).toContain('isometric');
        for (const s of GRID_STYLES) expect(s.label.length).toBeGreaterThan(0);
    });
});

describe("latticeSnap — square styles", () => {
    it("snaps to the square lattice, unchanged from plain grid snapping", () => {
        expect(latticeSnap(23, 37, G, 'lines')).toEqual({ x: 20, y: 40 });
        expect(latticeSnap(-11, -31, G, 'dots')).toEqual({ x: -20, y: -40 });
    });
});

/** Is this point on the lattice generated by a style's first two families? */
const onLattice = (p: { x: number; y: number }, g: number, style: any) => {
    const [a1, a2] = gridFamilyAngles(style);
    for (const a of [a1, a2]) {
        // Distance along the family's NORMAL must be an integer multiple of the spacing.
        const d = p.x * -Math.sin(a) + p.y * Math.cos(a);
        const k = d / g;
        if (Math.abs(k - Math.round(k)) > 1e-6) return false;
    }
    return true;
};

describe("latticeSnap — angled styles", () => {
    it("lands exactly on the diagonal lattice", () => {
        for (const [x, y] of [[0, 0], [13, 7], [-31, 52], [100, -3], [7.5, 7.5]]) {
            const p = latticeSnap(x, y, G, 'diagonal');
            expect(onLattice(p, G, 'diagonal'), `(${x},${y}) → (${p.x},${p.y})`).toBe(true);
        }
    });

    it("lands exactly on the isometric lattice", () => {
        for (const [x, y] of [[0, 0], [13, 7], [-31, 52], [100, -3]]) {
            const p = latticeSnap(x, y, G, 'isometric');
            expect(onLattice(p, G, 'isometric'), `(${x},${y}) → (${p.x},${p.y})`).toBe(true);
        }
    });

    it("never moves a point further than one cell away", () => {
        // A snap that teleports is worse than no snap. The lattice cell for spacing g has a
        // circumradius below g, so g is a safe bound and a real regression guard.
        for (const style of ['diagonal', 'isometric'] as const) {
            for (let i = 0; i < 60; i++) {
                const x = ((i * 37) % 400) - 200;
                const y = ((i * 91) % 400) - 200;
                const p = latticeSnap(x, y, G, style);
                expect(Math.hypot(p.x - x, p.y - y), `${style} at (${x},${y})`).toBeLessThan(G);
            }
        }
    });

    it("is idempotent — snapping a snapped point changes nothing", () => {
        for (const style of ['diagonal', 'isometric'] as const) {
            const once = latticeSnap(37, -19, G, style);
            const twice = latticeSnap(once.x, once.y, G, style);
            expect(twice.x).toBeCloseTo(once.x, 9);
            expect(twice.y).toBeCloseTo(once.y, 9);
        }
    });

    it("keeps the origin fixed, so the lattice is anchored at world 0,0", () => {
        for (const style of ['diagonal', 'isometric'] as const) {
            const p = latticeSnap(0, 0, G, style);
            expect(p.x).toBeCloseTo(0, 9);
            expect(p.y).toBeCloseTo(0, 9);
        }
    });

    it("survives a nonsense spacing rather than emitting NaN", () => {
        for (const style of ['diagonal', 'isometric'] as const) {
            for (const g of [0, -5, NaN]) {
                const p = latticeSnap(13, 7, g, style);
                expect(Number.isFinite(p.x) && Number.isFinite(p.y), `${style} g=${g}`).toBe(true);
            }
        }
    });
});
